// 请使用@形式去引用，不要使用相对路径！！！！！
import CmsListView from '@/desktop/components/listview'
import {
  evaluateColumns,
  frameInfoColumns,
  frameBudgeColumns,
  supplierColumns,
  projectColumns,
  outStaffInfoColumns,
  selectConfirmColumns,
  levelColumns,
  outStaffInfo,
  supplierOutStaffInfo,
  contractList,
  supplierPostPriceList,
  postColumns,
  projectSelectInfocolumns,
  staffReviewColumns,
  cmsProjectInterviewList,
  cmsProjectWrittenList,
  attendDataColumns,
  criertiaObj
} from '@/desktop/commonColumns/index'
export {
  CmsListView,
  evaluateColumns,
  frameInfoColumns,
  frameBudgeColumns,
  supplierColumns,
  projectColumns,
  outStaffInfoColumns,
  selectConfirmColumns,
  levelColumns,
  outStaffInfo,
  supplierOutStaffInfo,
  contractList,
  supplierPostPriceList,
  postColumns,
  projectSelectInfocolumns,
  staffReviewColumns,
  cmsProjectInterviewList,
  cmsProjectWrittenList,
  attendDataColumns,
  criertiaObj
}